name: mix_cafe_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  animated_notch_bottom_bar: ^1.0.3
  awesome_snackbar_content: ^0.1.6
  bloc: ^9.0.0
  bottom_bar: ^2.0.5
  buttons_tabbar: ^1.3.15
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.10
  crystal_navigation_bar: ^1.0.4
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dotted_border: ^3.0.1
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.0
  hydrated_bloc: ^10.0.0
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  introduction_screen: ^4.0.0
  local_hero_transform: ^1.0.6
  lottie: ^3.3.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  water_drop_nav_bar: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/lang/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: null
