name: mix_cafe_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  animated_notch_bottom_bar: ^1.0.3
  buttons_tabbar: ^1.3.15
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dotted_border: ^3.0.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  local_hero_transform: ^1.0.6
  water_drop_nav_bar: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: null
