// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiL3z5jXfsBv2J0EorHsQ7mMFtiby8fGA',
    appId: '1:1048408314340:web:cd9a2eaf2d90dc3322b7f1',
    messagingSenderId: '1048408314340',
    projectId: 'mix-cafe-app',
    authDomain: 'mix-cafe-app.firebaseapp.com',
    storageBucket: 'mix-cafe-app.firebasestorage.app',
    measurementId: 'G-B692VTDTGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb1fmt2olvY7PnNL0HRxhsvL0pB3InN_E',
    appId: '1:1048408314340:android:262f677b2870a41622b7f1',
    messagingSenderId: '1048408314340',
    projectId: 'mix-cafe-app',
    storageBucket: 'mix-cafe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WNQD4pizpMa5eE8Rfa4MsJhJruCWZWE',
    appId: '1:1048408314340:ios:03fb68d7bfce22d722b7f1',
    messagingSenderId: '1048408314340',
    projectId: 'mix-cafe-app',
    storageBucket: 'mix-cafe-app.firebasestorage.app',
    iosBundleId: 'com.example.mixCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3WNQD4pizpMa5eE8Rfa4MsJhJruCWZWE',
    appId: '1:1048408314340:ios:127bfdeb6ca14e3122b7f1',
    messagingSenderId: '1048408314340',
    projectId: 'mix-cafe-app',
    storageBucket: 'mix-cafe-app.firebasestorage.app',
    iosBundleId: 'com.example.mixCafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiL3z5jXfsBv2J0EorHsQ7mMFtiby8fGA',
    appId: '1:1048408314340:web:72781c5a9b83809322b7f1',
    messagingSenderId: '1048408314340',
    projectId: 'mix-cafe-app',
    authDomain: 'mix-cafe-app.firebaseapp.com',
    storageBucket: 'mix-cafe-app.firebasestorage.app',
    measurementId: 'G-ERQ49326HR',
  );

}